
enum RocketStatus {
    PREPARATION = 0,
    ON_INTERNAL_POWER = 1,
    STARTUP = 2,
    MAIN_ENGINE_STARTED = 3,
    LAUNCHED = 4,
    MAX_Q_REACHED = 5,
    MAIN_ENGINE_CUT_OFF = 6,
    BOOSTER_DETACHED = 7,
    SECOND_ENGINE_START = 8,
    FAIRING_SEPARATION = 9,
    SECOND_ENGINE_CUT_OFF = 10,
    DESTROYED = 99,
}

export default RocketStatus;


