language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: weather
      script:
        - cd back/weather-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: real-time
      script:
        - cd back/real-time-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: rocket
      script:
        - cd back/rocket-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: mission
      script:
        - cd back/mission-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: telemetry-writer
      script:
        - cd back/telemetry-writer-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: telemetry-listener
      script:
        - cd back/telemetry-listener-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: payload
      script:
        - cd back/payload-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: booster
      script:
        - cd back/booster-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: front
      script:
        - cd front
        - cp .env.travis .env
        - npm install
        - npm run build
    - stage: client #Run cucumber (todo do only on master)
      script:
        - docker-compose up --build --exit-code-from front
      after-script:
        - docker-compose kill
      if: branch = master OR branch = release OR branch = test-ci OR type = pull_request

notifications:
  slack: informatiquep-kyw7477:InXvtw4L5aLweMKgjOygoiZB