language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: weather
      script:
        - cd back/weather-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: rocket
      script:
        - cd back/rocket-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: mission
      script:
        - cd back/mission-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: telemetry
      script:
        - cd back/telemetry-service
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: front
      script:
        - cd front
        - cp .env.travis .env
        - npm install
        - npm run build
    - stage: client #Run cucumber (todo do only on master)
      script:
        - docker-compose up --build --exit-code-from front
      after-script:
        - docker-compose kill
      if: branch = master OR branch = release OR branch = test-ci

notifications:
  slack: informatiquep-kyw7477:InXvtw4L5aLweMKgjOygoiZB