language: node_js
node_js:
  - 14

jobs:
  include:
    - stage: weather
      script:
        - cd weather
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: rocket
      script:
        - cd rocket
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: command
      script:
        - cd command
        - cp .env.travis .env
        - npm install
        - npm run test
    - stage: client #Run cucumber (todo do only on master)
      script:
        - docker-compose build
        - docker-compose up -d
      after-script:
        - docker-compose kill

notifications:
  slack: informatiquep-kyw7477:InXvtw4L5aLweMKgjOygoiZB