version: "3"

services:
  waitforservices:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rocket-service
      - weather-service 
      - mission-service  
    command: rocket-service:3000 weather-service:3001 mission-service:3002

  mission-service:
      image: blue_origin/mission-service
      container_name: mission-container
      build: ./back/mission-service
      expose: 
        - "3002"
      ports:
        - "3002:3002"
      environment:
        - PORT=3002


  weather-service:
      image: blue-origin/weather-service
      container_name: weather-container
      build: ./back/weather-service
      expose: 
        - "3001"
      ports:
        - "3001:3001"
      environment:
        - PORT=3001


  rocket-service:
      image: blue-origin/rocket-service
      container_name: rocket-container
      build: ./back/rocket-service
      expose: 
        - "3000"
      ports:
        - "3000:3000"
      environment:
        - PORT=3000


  front:
      image: blue-origin/front
      container_name: front-container
      build: ./front
      environment:
        - HOST_ROCKET=rocket-service
        - PORT_ROCKET=3000
        - HOST_WEATHER=weather-service
        - PORT_WEATHER=3001
        - HOST_MISSION=mission-service
        - PORT_MISSION=3002
      depends_on:
        - rocket-service
        - weather-service
        - mission-service
        - waitforservices
      stdin_open: true
      tty: true
    
