version: "3"

services:
  waitforservices:
    image: dadarek/wait-for-dependencies
    depends_on:
      - rocket-service
      - weather-service 
      - mission-service
      - telemetry-service
      - booster-service
      - payload-service
      - real-time-service
    command: rocket-service:3000 weather-service:3001 mission-service:3002 telemetry-service:3003 booster-service:3004 payload-service:3005 real-time-service:3006

  telemetry-service:
    image: blue_origin/telemetry-service
    container_name: telemetry-container
    build: 
      context: .
      dockerfile: ./back/telemetry-service/Dockerfile
    expose:
      - "3003"
    ports:
      - "3003:3003"
    volumes:
      - ./container-logs:/usr/src/app/logs
    environment:
      - PORT=3003

  mission-service:
      image: blue_origin/mission-service
      container_name: mission-container
      build: 
        context: .
        dockerfile: ./back/mission-service/Dockerfile
      expose: 
        - "3002"
      ports:
        - "3002:3002"
      volumes:
        - ./container-logs:/usr/src/app/logs
      environment:
        - PORT=3002


  weather-service:
      image: blue-origin/weather-service
      container_name: weather-container
      build: 
        context: .
        dockerfile: ./back/weather-service/Dockerfile
      expose: 
        - "3001"
      ports:
        - "3001:3001"
      volumes:
        - ./container-logs:/usr/src/app/logs
      environment:
        - PORT=3001

  real-time-service:
      image: blue-origin/real-time-service
      container_name: real-time-container
      build: 
        context: .
        dockerfile: ./back/real-time-service/Dockerfile
      expose: 
        - "3006"
      ports:
        - "3006:3006"
      volumes:
        - ./container-logs:/usr/src/app/logs
      environment:
        - PORT=3006

<<<<<<< HEAD
=======
  rocket-service:
    image: blue-origin/rocket-service
    container_name: rocket-container
    build:
      context: .
      dockerfile: ./back/rocket-service/Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    volumes:
      - ./container-logs:/usr/src/app/logs
    environment:
      - PORT=3000
      - HOST_TELEMETRY=telemetry-service
      - PORT_TELEMETRY=3003
      - HOST_BOOSTER=booster-service
      - PORT_BOOSTER=3004
      - HOST_MISSION=mission-service
      - PORT_MISSION=3002
    depends_on:
      - telemetry-service
>>>>>>> 5e91da6... #146 Added routes in Mission service for rocket mission status.

  rocket-service:
      image: blue-origin/rocket-service
      container_name: rocket-container
      build: 
        context: .
        dockerfile: ./back/rocket-service/Dockerfile
      expose: 
        - "3000"
      ports:
        - "3000:3000"
      volumes:
        - ./container-logs:/usr/src/app/logs
      environment:
        - PORT=3000
        - HOST_TELEMETRY=telemetry-service
        - PORT_TELEMETRY=3003
      depends_on:
        - telemetry-service
  
  booster-service:
    image: blue-origin/booster-service
    container_name: booster-container
    build: 
      context: .
      dockerfile: ./back/booster-service/Dockerfile
    expose: 
      - "3004"
    ports:
      - "3004:3004"
    volumes:
      - ./container-logs:/usr/src/app/logs
    environment:
      - PORT=3004
      - HOST_ROCKET=rocket-service
      - PORT_ROCKET=3000
      - HOST_TELEMETRY=telemetry-service
      - PORT_TELEMETRY=3003
      - HOST_MISSION=mission-service
      - PORT_MISSION=3002


  payload-service:
    image: blue_origin/payload-service
    container_name: payload-container
    build: 
      context: .
      dockerfile: ./back/payload-service/Dockerfile
    expose:
      - "3005"
    ports:
      - "3005:3005"
    volumes:
      - ./container-logs:/usr/src/app/logs
    environment:
      - PORT=3005
      - HOST_TELEMETRY=telemetry-service
      - PORT_TELEMETRY=3003

  front:
      image: blue-origin/front
      container_name: front-container
      build: 
        context: .
        dockerfile: ./front/Dockerfile
      environment:
        - HOST_ROCKET=rocket-service
        - PORT_ROCKET=3000
        - HOST_WEATHER=weather-service
        - PORT_WEATHER=3001
        - HOST_MISSION=mission-service
        - PORT_MISSION=3002
        - HOST_TELEMETRY=telemetry-service
        - PORT_TELEMETRY=3003
        - HOST_BOOSTER=booster-service
        - PORT_BOOSTER=3004
        - HOST_PAYLOAD=payload-service
        - PORT_PAYLOAD=3005
        - HOST_REAL_TIME=real-time-service
        - PORT_REAL_TIME=3006
      depends_on:
        - rocket-service
        - weather-service
        - mission-service
        - telemetry-service
        - booster-service
        - payload-service
        - real-time-service
        - waitforservices
      stdin_open: true
      tty: true