version: "3"

services:
  mission-service:
      image: blue_origin/mission-service
      container_name: mission-container
      build: ./mission-service
      ports:
        - "3002:3002"
      environment:
        - PORT=3002


  weather-service:
      image: blue-origin/weather-service
      container_name: weather-container
      build: ./weather-service
      ports:
        - "3001:3001"
      environment:
        - PORT=3001


  rocket-service:
      image: blue-origin/rocket-service
      container_name: rocket-container
      build: ./rocket-service
      ports:
        - "3000:3000"
      environment:
        - PORT=3000


  client:
      image: blue-origin/client
      container_name: client-container
      build: ./client
      environment:
        - HOST_ROCKET=rocket-service
        - PORT_ROCKET=3000
        - HOST_WEATHER=weather-service
        - PORT_WEATHER=3001
        - HOST_MISSION=mission-service
        - PORT_MISSION=3002
      depends_on:
        - rocket-service
        - weather-service
        - mission-service
      stdin_open: true
      tty: true
    
