name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env: 
      working-directory: ./weather

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: ${{env.working-directory}}
    - run: npm run ci
      working-directory: ${{env.working-directory}}
      env:
        CI: true